# Sample configuration for sane-rss

# Polling interval in seconds (default: 300 seconds = 5 minutes)
polling_interval_seconds = 300
server_host = "127.0.0.1"
server_port = 8080

# Maximum number of items to keep per feed (default: 60)
max_items_per_feed = 60

[llm]
api_key = "YOUR_ANTHROPIC_API_KEY"
model = "claude-3-5-sonnet-20241022"
thinking_enabled = false
prompt = """
You are an RSS feed filter. Analyze the following RSS post and determine if it matches any of the provided topics.

Post title: {title}
Post description: {description}
Post content excerpt: {content_excerpt}

Accept topics: {accept_topics}
Reject topics: {reject_topics}

Return a JSON response with two boolean fields:
- "accept": true if the post matches any accept topics, otherwise false
- "reject": true if the post matches any reject topics, otherwise false

Both fields can be true at the same time. If both fields are true, the post will be accepted.

You must respond with valid JSON in exactly this format: {"accept": true/false, "reject": true/false}
"""

[global_filters]
accept = ["technology", "programming", "rust", "web development"]
reject = ["advertising", "sponsored content", "clickbait"]


[feeds.hackernews]
url = "https://news.ycombinator.com/rss"
[feeds.hackernews.filters]
accept = ["startup", "open source"]
reject = ["crypto", "blockchain"]

[feeds.techcrunch]
url = "https://techcrunch.com/feed/"
[feeds.techcrunch.filters]
accept = ["AI", "machine learning"]
reject = ["fundraising"]
